// Generates fhir/input/fsh/vocabulary.fsh: one CodeSystem per answer list, from
// the same sources the app uses (official OAH app vocabularies from the snapshot,
// StreamKeepers additions from checkForm). Usage: npm run fhir:vocab
import { writeFile } from "node:fs/promises";
import { join } from "node:path";
import { STEPS } from "../src/domain/checkForm";
import { answerSystem } from "../src/fhir/mapping";

// FSH strings use the same escaping as JSON strings.
const str = (s: string) => JSON.stringify(s);

async function main() {
  const seen = new Set<string>();
  const out: string[] = ["// GENERATED by scripts/fhir-vocab.ts from the app's answer lists. Do not edit.", ""];
  for (const q of STEPS.flatMap((s) => s.questions)) {
    const url = answerSystem(q.id);
    if (seen.has(url)) continue;
    seen.add(url);
    const official = url.includes("api.enora-oah.eu");
    const id = official ? `oah-app-${url.split("/").pop()!.replace(/_/g, "-")}` : url.split("/").pop()!;
    const name = id.split("-").map((w) => w[0].toUpperCase() + w.slice(1)).join("");
    out.push(`CodeSystem: ${name}`, `Id: ${id}`);
    out.push(`Title: ${str(official ? `OneAquaHealth Citizen Science App: ${q.term}` : `StreamKeepers: ${q.term}`)}`);
    out.push(`Description: ${str(official ? `Answer codes of the official OneAquaHealth Citizen Science App (${url}), as served by the public OneAquaHealth API.` : `Answer codes for a StreamKeepers question: ${q.title}`)}`);
    out.push(`* ^url = ${str(url)}`, "* ^status = #draft", "* ^caseSensitive = true", "* ^content = #complete");
    for (const o of q.options) out.push(`* #${o.code} ${str(o.official ?? o.label)}`);
    out.push("");
  }
  await writeFile(join(import.meta.dirname, "..", "fhir", "input", "fsh", "vocabulary.fsh"), out.join("\n"));
  console.log(`wrote ${seen.size} code systems`);
}

main();
