// Validates the example bundles (npm run fhir:examples) with the official HL7 FHIR
// validator against the OneAquaHealth IG and the StreamKeepers definitions, then
// writes eval/fhir/validation-summary.md. See docs/FHIR-VALIDATION.md.
//
// Env: JAVA_BIN (java executable), HL7_VALIDATOR (validator_cli.jar),
//      OAH_IG (folder with the OAH IG resources, e.g. hl7-eu/oah compiled by SUSHI).
import { spawnSync } from "node:child_process";
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const root = join(import.meta.dirname, "..");
const env = (k: string) => {
  const v = process.env[k];
  if (!v) throw new Error(`Set ${k} (see docs/FHIR-VALIDATION.md)`);
  return v;
};
const files = ["accepted-check.json", "held-check.json", "reviewed-check.json"].map((f) => join(root, "eval", "fhir", f));
const outcome = join(root, "eval", "fhir", "validation-outcome.json");

const args = [
  "-jar", env("HL7_VALIDATOR"), ...files, "-version", "4.0.1",
  "-ig", env("OAH_IG"),
  "-ig", join(root, "fhir", "fsh-generated", "resources"),
  "-ig", join(root, "fhir", "questionnaire"),
  "-output", outcome,
];
console.log("Running the HL7 validator (first run downloads FHIR packages and can take ~15 min)…");
const r = spawnSync(env("JAVA_BIN"), args, { encoding: "utf8", maxBuffer: 1 << 28 });
writeFileSync(join(root, "eval", "fhir", "validation.log"), (r.stdout ?? "") + (r.stderr ?? ""));
if (r.status !== 0 && !r.stdout?.includes("Done.")) throw new Error(`validator exited ${r.status}`);

type Issue = { severity: string; details?: { text?: string }; expression?: string[]; location?: string[] };
const doc = JSON.parse(readFileSync(outcome, "utf8"));
const oos: { issue?: Issue[]; extension?: { url: string; valueString?: string }[] }[] =
  doc.resourceType === "Bundle" ? doc.entry.map((e: { resource: unknown }) => e.resource) : [doc];

const L = ["# FHIR validation (official HL7 validator)", "", `Generated by \`npm run fhir:validate\` on ${new Date().toISOString().slice(0, 10)} (UTC).`, ""];
L.push("Validated against: FHIR R4 core, the OneAquaHealth IG (`hl7-eu/oah`, compiled from source with SUSHI because build.fhir.org was offline), the StreamKeepers definitions in [`fhir/`](../../fhir/) and the StreamKeepers Questionnaire.", "");
L.push("| Example | Errors | Warnings | Information |", "|---|---|---|---|");
const details: string[] = [];
for (const oo of oos) {
  const file = (oo.extension?.find((x) => x.url.includes("file"))?.valueString ?? "?").split(/[\\/]/).pop();
  const issues = oo.issue ?? [];
  const n = (s: string) => issues.filter((i) => i.severity === s || (s === "error" && i.severity === "fatal")).length;
  L.push(`| ${file} | ${n("error")} | ${n("warning")} | ${n("information")} |`);
  for (const i of issues.filter((x) => x.severity === "error" || x.severity === "fatal" || x.severity === "warning")) {
    details.push(`- **${file}** ${i.severity}: ${(i.expression ?? i.location ?? [""])[0]} — ${i.details?.text ?? ""}`);
  }
}
L.push("", details.length ? "## Remaining errors and warnings" : "No errors or warnings.", "", ...details, "");
writeFileSync(join(root, "eval", "fhir", "validation-summary.md"), L.join("\n"));
console.log(L.slice(4, 4 + 2 + oos.length).join("\n"));
