// Runs the season simulation and writes eval/sim_results.{md,json}.
// Usage: npm run simulate   (deterministic: same numbers every run)
import { mkdir, writeFile } from "node:fs/promises";
import { join } from "node:path";
import { buildSiteFacts } from "../src/domain/siteFacts";
import { DEFAULT_WEIGHTS } from "../src/domain/missionValue";
import { DEFAULT_PARAMS, metrics, prepareSites, SCHEMES, simulateSeason, type Metrics, type Scheme, type SimParams } from "../src/sim/model";

const RUNS = 200;
const SEASON_START = new Date("2026-09-01T00:00:00Z");
const research = buildSiteFacts().filter((s) => s.kind === "research");
const sites = prepareSites(research, SEASON_START);

type Summary = Record<keyof Metrics, { mean: number; lo: number; hi: number }>;

function summarise(ms: Metrics[]): Summary {
  const keys = Object.keys(ms[0]) as (keyof Metrics)[];
  return Object.fromEntries(
    keys.map((k) => {
      const v = ms.map((m) => m[k]).sort((a, b) => a - b);
      return [k, { mean: v.reduce((a, b) => a + b, 0) / v.length, lo: v[Math.floor(v.length * 0.025)], hi: v[Math.ceil(v.length * 0.975) - 1] }];
    }),
  ) as Summary;
}

function run(over: Partial<SimParams>, simSites = sites): Record<Scheme, Summary> {
  const out = {} as Record<Scheme, Summary>;
  for (const scheme of SCHEMES) {
    const ms: Metrics[] = [];
    // Same seeds for every scheme: each comparison is paired (same volunteers, same homes).
    for (let seed = 1; seed <= RUNS; seed++) ms.push(metrics(simSites, simulateSeason(simSites, scheme, { ...DEFAULT_PARAMS, ...over, seed })));
    out[scheme] = summarise(ms);
  }
  return out;
}

const pct = (x: number) => `${(x * 100).toFixed(0)}%`;
const range = (s: { lo: number; hi: number }, f: (x: number) => string) => `${f(s.lo)}–${f(s.hi)}`;
const NAMES: Record<Scheme, string> = {
  flat: "Classic: 10 pts per report",
  value: "StreamKeepers (OAH data)",
  valueNoOah: "StreamKeepers without OAH data",
};

async function main() {
  const t0 = Date.now();
  const main = run({});
  const betas = [0, 0.5, 1, 2].map((b) => ({ b, r: run({ betaPoints: b }) }));
  const crowds = [10, 20, 40].map((v) => ({ v, r: run({ volunteersPerCity: v }) }));
  // Policy what-if: the coordinator's lab-risk weight (default 30). Not the headline.
  const riskWeights = [0, 30, 60, 90].map((w) => ({ w, r: run({}, prepareSites(research, SEASON_START, { ...DEFAULT_WEIGHTS, labRisk: w })) }));

  const risks = research.map((s) => s.labRiskScore).filter((x): x is number => x !== null);
  const L: string[] = [];
  L.push("# Season simulation: where do volunteer checks go?", "");
  L.push("> **Simulated volunteers, real sites.** The 106 OneAquaHealth research sites, their lab health-risk scores, lab dates and population near the water are real (ENORA API snapshot). The volunteers and their choices are a model, described below. These numbers show how the scoring rules steer effort *under these assumptions*; they are not field results.", "");
  L.push(`Generated by \`npm run simulate\` (deterministic, ${RUNS} paired runs per scenario, seeds 1–${RUNS}). Mission values come from the app's own \`missionValue()\`.`, "");
  const few = crowds.find((c) => c.v === 10)!.r;
  const unchecked = (x: number) => 1 - x;
  const fewer = (a: number, b: number) => Math.round((100 * (unchecked(a) - unchecked(b))) / unchecked(a));
  L.push("## Findings", "");
  L.push(`1. **Fewer forgotten streams.** Value-priced missions leave fewer sites unchecked in a season than classic flat points, at the same median trip length (${main.value.medianTravelKm.mean.toFixed(1)} km): ${pct(unchecked(main.flat.coverage.mean))} → ${pct(unchecked(main.value.coverage.mean))} of sites unchecked with ${DEFAULT_PARAMS.volunteersPerCity} volunteers per city, and ${pct(unchecked(few.flat.coverage.mean))} → ${pct(unchecked(few.value.coverage.mean))} with 10 per city (${fewer(few.flat.coverage.mean, few.value.coverage.mean)}% fewer unchecked sites).`);
  L.push(`2. **High-risk sites are checked more often at least once:** ${pct(few.flat.highRiskCoverage.mean)} → ${pct(few.value.highRiskCoverage.mean)} with 10 volunteers per city, ${pct(main.flat.highRiskCoverage.mean)} → ${pct(main.value.highRiskCoverage.mean)} with ${DEFAULT_PARAMS.volunteersPerCity}.`);
  L.push(`3. **Most of the gain comes from pricing by coverage; the OAH data adds a smaller part.** Without OAH data the same code reaches ${pct(few.valueNoOah.coverage.mean)} coverage and ${pct(few.valueNoOah.highRiskCoverage.mean)} high-risk coverage (10 volunteers per city), versus ${pct(few.value.coverage.mean)} and ${pct(few.value.highRiskCoverage.mean)} with it.`);
  L.push(`4. **Points do not pull volunteers to distant high-risk sites.** The share of all checks made at high-risk sites barely moves (${pct(main.flat.highRiskShare.mean)} → ${pct(main.value.highRiskShare.mean)}), even with a three times larger risk weight (see what-if). Volunteers check streams near home; reaching far high-risk sites needs other levers (lab visits, organised outings).`);
  L.push(`5. **Crowding at the busiest sites is unchanged** (${pct(main.flat.top10Share.mean)} → ${pct(main.value.top10Share.mean)} of checks on the 10% busiest sites): popular places stay popular; the gain is at the other end, on sites nobody visited.`, "");
  L.push("## Headline (default assumptions)", "");
  L.push("| Scoring rule | Sites checked this season | Highest-risk quartile checked | Share of checks at highest-risk sites | Checks on the 10% busiest sites | Median trip |");
  L.push("|---|---|---|---|---|---|");
  for (const s of SCHEMES) {
    const m = main[s];
    L.push(`| ${NAMES[s]} | **${pct(m.coverage.mean)}** (${range(m.coverage, pct)}) | **${pct(m.highRiskCoverage.mean)}** (${range(m.highRiskCoverage, pct)}) | **${pct(m.highRiskShare.mean)}** (${range(m.highRiskShare, pct)}) | ${pct(m.top10Share.mean)} | ${m.medianTravelKm.mean.toFixed(1)} km |`);
  }
  L.push("", `The highest-risk quartile is ${Math.round(100 * sites.filter((x) => x.site.labRiskScore !== null).length / 4 / sites.length)}% of sites, so a rule that ignores risk sends about that share of checks there.`);
  L.push("", `Total checks per season are the same for every rule (≈${Math.round(main.flat.totalChecks.mean)}): the rules only change *where* volunteers go. Ranges are the 2.5–97.5 percentiles over ${RUNS} runs.`, "");

  L.push("## How much do volunteers care about points? (sensitivity)", "");
  L.push("`betaPoints` is the assumption that matters most: how strongly a volunteer's choice follows points (0 = points are ignored).", "");
  L.push("| betaPoints | Classic: sites checked | StreamKeepers: sites checked | Without OAH data: sites checked | Classic: high-risk | StreamKeepers: high-risk | Without OAH data: high-risk |");
  L.push("|---|---|---|---|---|---|---|");
  for (const { b, r } of betas) {
    L.push(`| ${b}${b === DEFAULT_PARAMS.betaPoints ? " (default)" : ""} | ${pct(r.flat.coverage.mean)} | ${pct(r.value.coverage.mean)} | ${pct(r.valueNoOah.coverage.mean)} | ${pct(r.flat.highRiskCoverage.mean)} | ${pct(r.value.highRiskCoverage.mean)} | ${pct(r.valueNoOah.highRiskCoverage.mean)} |`);
  }
  L.push("", "At betaPoints = 0 all three rules give identical results (checked by a unit test): the scoring cannot help if people ignore it.", "");

  L.push("## More or fewer volunteers", "");
  L.push("| Volunteers per city | Classic: sites checked | StreamKeepers: sites checked | Without OAH data | Classic: high-risk checked | StreamKeepers: high-risk checked | Without OAH data: high-risk checked | Classic: share at high-risk | StreamKeepers: share at high-risk | Without OAH data: share at high-risk |");
  L.push("|---|---|---|---|---|---|---|---|---|---|");
  for (const { v, r } of crowds) {
    L.push(`| ${v}${v === DEFAULT_PARAMS.volunteersPerCity ? " (default)" : ""} | ${pct(r.flat.coverage.mean)} | ${pct(r.value.coverage.mean)} | ${pct(r.valueNoOah.coverage.mean)} | ${pct(r.flat.highRiskCoverage.mean)} | ${pct(r.value.highRiskCoverage.mean)} | ${pct(r.valueNoOah.highRiskCoverage.mean)} | ${pct(r.flat.highRiskShare.mean)} | ${pct(r.value.highRiskShare.mean)} | ${pct(r.valueNoOah.highRiskShare.mean)} |`);
  }

  L.push("", "## What-if: the coordinator's lab-risk weight", "");
  L.push("The default weights add at most 30 points for lab health risk. That turns out to be too weak to move much effort towards high-risk sites: distance and popularity dominate. Because the weights are a coordinator setting, this table shows what a stronger risk weight would do, and what it costs in travel. The headline above keeps the default.", "");
  L.push("| Lab-risk weight | Sites checked | High-risk quartile checked | Share of checks at high-risk sites | Median trip |");
  L.push("|---|---|---|---|---|");
  for (const { w, r } of riskWeights) {
    const m = r.value;
    L.push(`| ${w}${w === DEFAULT_WEIGHTS.labRisk ? " (default)" : ""} | ${pct(m.coverage.mean)} | ${pct(m.highRiskCoverage.mean)} | ${pct(m.highRiskShare.mean)} | ${m.medianTravelKm.mean.toFixed(1)} km |`);
  }
  L.push("", `Classic flat points for reference: ${pct(main.flat.highRiskShare.mean)} of checks at high-risk sites.`);

  L.push("", "## Model and assumptions", "");
  L.push(`- **Sites:** ${sites.length} OAH research sites in 5 cities. Citizen-created sites are left out: they are scattered across Europe with no local volunteer pool to model.`);
  L.push(`- **Highest-risk quartile:** sites whose OAH lab health-risk score is ≥ the 75th percentile (${risks.length} sites have a score).`);
  L.push(`- **Volunteers:** ${DEFAULT_PARAMS.volunteersPerCity} per city, living near sites weighted by population (people live where people live), ±1.5 km.`);
  L.push(`- **Season:** ${DEFAULT_PARAMS.weeks} weeks; each week a volunteer checks one stream with probability ${DEFAULT_PARAMS.tripProb} (≈${(DEFAULT_PARAMS.weeks * DEFAULT_PARAMS.tripProb).toFixed(1)} checks each).`);
  L.push(`- **Choice:** softmax over sites within ${DEFAULT_PARAMS.maxKm} km of utility = −distance/${DEFAULT_PARAMS.distScaleKm} km + ${DEFAULT_PARAMS.alphaPopularity} × popularity (population percentile) + betaPoints × points/100.`);
  L.push("- **Classic rule:** every check is worth 10 points, so points don't steer the choice.");
  L.push("- **StreamKeepers:** the app's mission value (lab staleness, season gap, lab risk, people nearby, divided by 1 + checks already made this season), recomputed after every check.");
  L.push("- **Without OAH data (ablation):** the same code with lab dates, lab risk and population removed. What remains is the season gap and the crowding discount.");
  L.push("- **Not modelled:** adopted streams, reminders, teams, weather, safety or access, volunteers dropping out. Every check is assumed to pass the quality gate.", "");
  L.push("## Limits", "");
  L.push("- The behaviour parameters are assumptions, not measured. The sensitivity table shows how results move with the key one.");
  L.push("- Lab staleness is at its cap for every site (all public lab campaigns are 2023–24), so in this data it adds the same points everywhere and does not steer choices.");
  L.push("- Popularity is proxied by population near the site, the only OAH variable available for it.");
  L.push("", `_Runtime ${((Date.now() - t0) / 1000).toFixed(1)} s._`);

  const dir = join(import.meta.dirname, "..", "eval");
  await mkdir(dir, { recursive: true });
  await writeFile(join(dir, "sim_results.md"), L.join("\n") + "\n");
  await writeFile(join(dir, "sim_results.json"), JSON.stringify({ runs: RUNS, seasonStart: SEASON_START, params: DEFAULT_PARAMS, weights: DEFAULT_WEIGHTS, main, betas, crowds, riskWeights }, null, 1) + "\n");
  console.log(L.slice(0, 12).join("\n"));
}

main();
