// GENERATED by scripts/fhir-vocab.ts from the app's answer lists. Do not edit.

CodeSystem: OahAppWaterFlows
Id: oah-app-water-flows
Title: "OneAquaHealth Citizen Science App: Water flow"
Description: "Answer codes of the official OneAquaHealth Citizen Science App (https://api.enora-oah.eu/api/citizens/water_flows), as served by the public OneAquaHealth API."
* ^url = "https://api.enora-oah.eu/api/citizens/water_flows"
* ^status = #draft
* ^caseSensitive = true
* ^content = #complete
* #FAS "Fast (with waves or high velocity)"
* #NOR "Slow"
* #STA "Stagnant/intermittent"
* #DRY "Dry"

CodeSystem: OahAppWaterColors
Id: oah-app-water-colors
Title: "OneAquaHealth Citizen Science App: Water aspect"
Description: "Answer codes of the official OneAquaHealth Citizen Science App (https://api.enora-oah.eu/api/citizens/water_colors), as served by the public OneAquaHealth API."
* ^url = "https://api.enora-oah.eu/api/citizens/water_colors"
* ^status = #draft
* ^caseSensitive = true
* ^content = #complete
* #CL "Clear/transparent"
* #MU "Muddy/turbid"
* #FO "Has foam"
* #CO "Has colors/altered color"

CodeSystem: OahAppChannelTypes
Id: oah-app-channel-types
Title: "OneAquaHealth Citizen Science App: Channel type"
Description: "Answer codes of the official OneAquaHealth Citizen Science App (https://api.enora-oah.eu/api/citizens/channel_types), as served by the public OneAquaHealth API."
* ^url = "https://api.enora-oah.eu/api/citizens/channel_types"
* ^status = #draft
* ^caseSensitive = true
* ^content = #complete
* #NAT "Natural"
* #ART "Artificial (concrete or stones with concrete)"

CodeSystem: OahAppChannelForms
Id: oah-app-channel-forms
Title: "OneAquaHealth Citizen Science App: Channel form"
Description: "Answer codes of the official OneAquaHealth Citizen Science App (https://api.enora-oah.eu/api/citizens/channel_forms), as served by the public OneAquaHealth API."
* ^url = "https://api.enora-oah.eu/api/citizens/channel_forms"
* ^status = #draft
* ^caseSensitive = true
* ^content = #complete
* #FLAT "Flat"
* #U "U Shape"
* #V "V Shape"

CodeSystem: OahAppBankTypes
Id: oah-app-bank-types
Title: "OneAquaHealth Citizen Science App: Bank type"
Description: "Answer codes of the official OneAquaHealth Citizen Science App (https://api.enora-oah.eu/api/citizens/bank_types), as served by the public OneAquaHealth API."
* ^url = "https://api.enora-oah.eu/api/citizens/bank_types"
* ^status = #draft
* ^caseSensitive = true
* ^content = #complete
* #NAT "Natural"
* #ART "Artificial (concrete or stones with concrete)"
* #LAS "Layed stones with no concrete"

CodeSystem: OahAppHabitats
Id: oah-app-habitats
Title: "OneAquaHealth Citizen Science App: Habitats"
Description: "Answer codes of the official OneAquaHealth Citizen Science App (https://api.enora-oah.eu/api/citizens/habitats), as served by the public OneAquaHealth API."
* ^url = "https://api.enora-oah.eu/api/citizens/habitats"
* ^status = #draft
* ^caseSensitive = true
* ^content = #complete
* #SB "Sand banks"
* #SI "Sand islands"
* #RF "Riffles, rapids, falls"
* #AV "Aquatic vegetation"
* #SD "Stone deposits"

CodeSystem: OahAppFallenBiomass
Id: oah-app-fallen-biomass
Title: "OneAquaHealth Citizen Science App: Natural debris (fallen biomass)"
Description: "Answer codes of the official OneAquaHealth Citizen Science App (https://api.enora-oah.eu/api/citizens/fallen_biomass), as served by the public OneAquaHealth API."
* ^url = "https://api.enora-oah.eu/api/citizens/fallen_biomass"
* ^status = #draft
* ^caseSensitive = true
* ^content = #complete
* #FT "Fallen trees"
* #FB "Fallen branches"
* #FL "Deposits of fallen leaves"

CodeSystem: StreamkeepersDrainingPipes
Id: streamkeepers-draining-pipes
Title: "StreamKeepers: Draining pipes"
Description: "Answer codes for a StreamKeepers question: Do pipes flow into the stream?"
* ^url = "https://github.com/BriceZemba/streamkeepers/fhir/CodeSystem/streamkeepers-draining-pipes"
* ^status = #draft
* ^caseSensitive = true
* ^content = #complete
* #NO "No pipes"
* #DRY_PIPE "Pipes, but nothing coming out"
* #FLOWING "Pipes with water coming out"

CodeSystem: StreamkeepersSewageSigns
Id: streamkeepers-sewage-signs
Title: "StreamKeepers: Signs of sewage (StreamKeepers addition)"
Description: "Answer codes for a StreamKeepers question: Any sewage smell, grey water or toilet paper?"
* ^url = "https://github.com/BriceZemba/streamkeepers/fhir/CodeSystem/streamkeepers-sewage-signs"
* ^status = #draft
* ^caseSensitive = true
* ^content = #complete
* #YES "Yes"
* #NO "No"

CodeSystem: StreamkeepersBarriers
Id: streamkeepers-barriers
Title: "StreamKeepers: Barriers"
Description: "Answer codes for a StreamKeepers question: Is something blocking the flow?"
* ^url = "https://github.com/BriceZemba/streamkeepers/fhir/CodeSystem/streamkeepers-barriers"
* ^status = #draft
* ^caseSensitive = true
* ^content = #complete
* #YES "Yes"
* #NO "No"

CodeSystem: StreamkeepersConstruction
Id: streamkeepers-construction
Title: "StreamKeepers: Construction"
Description: "Answer codes for a StreamKeepers question: Are there works in or next to the stream?"
* ^url = "https://github.com/BriceZemba/streamkeepers/fhir/CodeSystem/streamkeepers-construction"
* ^status = #draft
* ^caseSensitive = true
* ^content = #complete
* #YES "Yes"
* #NO "No"

CodeSystem: StreamkeepersInvasiveSpecies
Id: streamkeepers-invasive-species
Title: "StreamKeepers: Invasive species"
Description: "Answer codes for a StreamKeepers question: Did you see plants or animals that don't belong here?"
* ^url = "https://github.com/BriceZemba/streamkeepers/fhir/CodeSystem/streamkeepers-invasive-species"
* ^status = #draft
* ^caseSensitive = true
* ^content = #complete
* #YES "Yes"
* #NO "No"

CodeSystem: OahAppVegetationTypes
Id: oah-app-vegetation-types
Title: "OneAquaHealth Citizen Science App: Vegetation, left margin"
Description: "Answer codes of the official OneAquaHealth Citizen Science App (https://api.enora-oah.eu/api/citizens/vegetation_types), as served by the public OneAquaHealth API."
* ^url = "https://api.enora-oah.eu/api/citizens/vegetation_types"
* ^status = #draft
* ^caseSensitive = true
* ^content = #complete
* #H "Herbs"
* #B "Shrubs"
* #T "Trees"

CodeSystem: StreamkeepersImpervious
Id: streamkeepers-impervious
Title: "StreamKeepers: Impervious areas"
Description: "Answer codes for a StreamKeepers question: How much of the banks is paved or built on?"
* ^url = "https://github.com/BriceZemba/streamkeepers/fhir/CodeSystem/streamkeepers-impervious"
* ^status = #draft
* ^caseSensitive = true
* ^content = #complete
* #NONE "None"
* #SOME "Some"
* #MOST "Most"

CodeSystem: OahAppStreamAssessments
Id: oah-app-stream-assessments
Title: "OneAquaHealth Citizen Science App: Overall stream assessment"
Description: "Answer codes of the official OneAquaHealth Citizen Science App (https://api.enora-oah.eu/api/citizens/stream_assessments), as served by the public OneAquaHealth API."
* ^url = "https://api.enora-oah.eu/api/citizens/stream_assessments"
* ^status = #draft
* ^caseSensitive = true
* ^content = #complete
* #GOOD "Good quality"
* #MODERATE "Moderate quality"
* #POOR "Poor quality"
